Javascript/javascript1/week3
Mamidi001/hyf-homework pull request #6
Opened 2021-11-13 15:46 UTC by Mamidi001

2021-11-13 20:46 UTC, aina21 commented on javascript/javascript1/week2/index.js
> +    if(firstname===" "&& surname===" "){
Do you mean `firstname===""` ?

2021-11-13 20:48 UTC, aina21 requested changes
Remove irrelevant files of week2 from this PR.

2021-11-13 20:50 UTC, aina21 commented on javascript/javascript1/week3/index.js
> +  //replace with different index in the array
it's better to have a function to get an id and values to replace.

2021-11-13 20:52 UTC, aina21 commented on javascript/javascript1/week3/index2.js
> +        const object ={
object is not a good name

2021-11-13 20:54 UTC, aina21 commented on javascript/javascript1/week3/index3.js
> +  names.splice(1,1);
names.splice(namesToRemove,1)

2021-11-13 20:54 UTC, aina21 commented on javascript/javascript1/week3/index4.js
> +      let journeyDuration = travelInformation.destinationDistance/ travelInformation.speed;//8.64
const

2021-11-13 20:55 UTC, aina21 requested changes
good job :+1:

2021-11-15 11:39 UTC, Mamidi001 commented on javascript/javascript1/week3/index3.js
> +  names.splice(1,1);
Ok i will change.

2021-11-15 11:40 UTC, Mamidi001 commented on javascript/javascript1/week3/index4.js
> +      let journeyDuration = travelInformation.destinationDistance/ travelInformation.speed;//8.64
Done

2021-11-15 11:41 UTC, Mamidi001 commented on javascript/javascript1/week3/index2.js
> +        const object ={
changed the object as activityInfo

2021-11-15 11:54 UTC, merged